# Generated by Django 5.1.5 on 2025-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
