# Generated by Django 5.1.5 on 2025-01-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_album_songs_alter_artist_bio_delete_song_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="notes_as_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
